import type { Metadata } from "next";
import { notoSansSC } from "@/components/ui/font";
import { Toaster } from "sonner";
// import { MasterDataProvider } from "@/providers/master-data-provider"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansSC.variable} antialiased`}>
        {/* <MasterDataProvider>*/}
        {children}
        <Toaster richColors position="top-right" />
        {/* </MasterDataProvider> */}
      </body>
    </html>
  );
}
